### ISSUE TITLE
Ladder system

### ISSUE THREAD

**Issue by denisolek** [ninjalulz/forgottenserver#11]
Ladders doesn't work when there is any item over it. 
![suysi9x](https://cloud.githubusercontent.com/assets/12300241/13791634/5f6c2792-eaee-11e5-9667-c605bb95aa19.gif)

(ps sorry for green areas, some recording error)

**Comment by dbjorkholm** [comment]
This were fixed in https://github.com/ninjalulz/forgottenserver/commit/b4be689e5800a72f5fee147e74c3e7282e9dd4c3. Have you updated your items.otb since then?

**Comment by denisolek** [comment]
You're right, i had old otb file. Thank you
