### ISSUE TITLE
How to compile this in visual studio 2019

### ISSUE THREAD

**Issue by woeterman94** [ninjalulz/forgottenserver#22]
Is it possible to compile this in visual studio 2019? If so how?

**Comment by woeterman94** [comment]
@ninjalulz does this work with vcpkg as described here: https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29

Edit: would be cool if someone made a tutorial on how to get this working in 2021..

**Comment by celohere** [comment]
You can compile with visual studio 2015 and 2017.https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows

**Comment by woeterman94** [comment]
Okay it worked! I had to change the compiler to use the v140 (visual studio 2015) toolset.
