### ISSUE TITLE
Walking around

### ISSUE THREAD

**Issue by Justikar** [ninjalulz/forgottenserver#5]
----- 29/02/2016 21:26:32 - Seven (191.187.54.131) -----
Debug Assertion 8.0 Communication.cpp 1765
Tue Mar 01 00:26:30 2016
Windows Version: 6.1 build 7600 on 2
Graphic Engine: DirectX9 (2)
Last Packet Types: 109 109 109 109 109 109 110 131 143 109
Last Packet: 058 000 109 133 129 132 123 015 001 133 129 131 123 015 160 150
Player Position: [33154,31620,15]
Player Name: Seven
Player.cpp 358: exception occurred, reason:
Network.cpp 980: exception occurred (ErrorCode = 0), reason:
Control.cpp 1309: exception occurred (Type = 109), reason:
Communication.cpp 1994: exception occurred, reason:
Communication.cpp 1765: Player object is not where it should be, reason:
 hx: 8 hy: 6 hz: 2
 Cylinder (1):  (410,0) (99,1073760013)
 Cylinder (2):  (410,0) (99,1073760013)(-)(-)(-)(-)(-)(-)(-)(-)
Comment:

**Comment by dbjorkholm** [comment]
Can you check if https://github.com/ninjalulz/forgottenserver/commit/e0542ae11182fcabc2fc74562c7e67cc5b1c389b fixes this?

**Comment by Justikar** [comment]
Fixed.
