### ISSUE TITLE
Ghost Debug client

### ISSUE THREAD

**Issue by Justikar** [ninjalulz/forgottenserver#7]
Get debug when use command /ghost, but when i back, im invisible.

----- 01/03/2016 19:33:29 - Seven (191.187.54.131) -----
Debug Assertion 8.0 Container.h 226
Tue Mar 01 22:33:42 2016
Windows Version: 6.1 build 7600 on 2
Graphic Engine: DirectX9 (2)
Last Packet Types: 131 180 142 132 131 140 109 109 109 109
Last Packet: 042 000 142 002 000 000 016 000 000 000 000 180 022 022 000 089
Player Position: [33135,31629,14]
Player Name: Seven
Player.cpp 358: exception occurred, reason:
Player.cpp 460: exception occurred, reason:
Control.cpp 1633: exception occurred (MessageType: 0 MaW: 7C7D78 MoW: 0), reason:
Control.cpp 1628: exception occurred, reason:
Control.cpp 379: exception occurred (Force?1:0 = 0), reason:
MainWindow.cpp 133: exception occurred (Surface = 1), reason:
GUI.cpp 1452: exception occurred (Surface = 1), reason:
MapWindow.cpp 861: exception occurred (Surface = 1), reason:
MapWindow.cpp 548: exception occurred (Obj = 0), reason:
MapWindow.cpp 1113: exception occurred (posx = 224) (posy = 160), reason:
MapWindow.cpp 1105: exception occurred (EffectNumber = 5) (Type = 0), reason:
Objects.cpp 691: exception occurred (Number = 0), reason:
Container.h 226: index out of range (original i: 0, i: -1, min: 1, d: 69)
Comment:

**Comment by dbjorkholm** [comment]
Fixed in https://github.com/ninjalulz/forgottenserver/commit/3ef7ba6def52569103cfffafb0fe3f8cc0c32fe9
