### ISSUE TITLE
NPC chat visible only for the player who said "hi"

### ISSUE THREAD

**Issue by Tamakero** [ninjalulz/forgottenserver#8]
First - thanks for fixing the NPCs/spells/monsters, thats a lot of awesome work! Second - while I was testing some changes today with my cousin, by accident we noticed that NPC dialogue is visible only to the player who started the talk (said "hi"), which I think is invalid because NPCs talk in Default Channel now, so it should be visible to everyone. I tried to fix this, but I'm complete newbie at programming and I obviously failed. It was tested on a server downloaded and compiled about 20 hours ago.

**Comment by mattyx14** [comment]
the old npc system are this the NPC dialogs are "visible for all players"... I remember this

**Comment by dbjorkholm** [comment]
Should be fixed in https://github.com/ninjalulz/forgottenserver/commit/60107d74244442b00ba8aac0ac8e2d0aa3faeec9.
