### ISSUE TITLE
NPC Shop module

### ISSUE THREAD

**Issue by denisolek** [ninjalulz/forgottenserver#9]
Shop module doesn't work.
Just try to summon Eryn or Deruno. Both have it scripted different way, noone works.
![npc](https://cloud.githubusercontent.com/assets/12300241/13553879/377e524e-e398-11e5-8498-c20b57df4618.jpg)

**Comment by dbjorkholm** [comment]
It's because the capacity is 0. It should work for normal characters though.

**Comment by denisolek** [comment]
Damn, im sorry... Tested on 3 different characters all of them had 0 capacity. 
Thank you anyway :)

**Comment by dbjorkholm** [comment]
I'll look into this later, and hopefully find out why the capacity is shown as 0 when it's not supposed to.

**Comment by deniso95** [comment]
I've tested it at rl tibia, prices show normally with 0 cap 
![prices](https://cloud.githubusercontent.com/assets/12300241/13553995/24b4abf0-e39c-11e5-9346-f891e4e8e020.jpg)

**Comment by Justikar** [comment]
0 cap, but the item is 0.10.
When you have 0 cap you still buy item with 0.x
